/* Autogenerated by hxtools bin2c */
#ifndef NWIPE_EXCLAMATION_JPG_H
#define NWIPE_EXCLAMATION_JPG_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_nwipe_exclamation_jpg[74292];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* NWIPE_EXCLAMATION_JPG_H */
