/* Autogenerated by hxtools bin2c */
#ifndef REDCROSS_H
#define REDCROSS_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_redcross_jpg[60331];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* REDCROSS_H */
