/* Autogenerated by hxtools bin2c */
#ifndef SHRED_DB_JPG_H
#define SHRED_DB_JPG_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_shred_db_jpg[27063];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* SHRED_DB_JPG_H */
