/* Autogenerated by hxtools bin2c */
#ifndef TICK_ERASED_JPG_H
#define TICK_ERASED_JPG_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_te_jpg[54896];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* TICK_ERASED_JPG_H */
