/**
 * version_string and program_name are used by siege
 * and configure; author_name and email_address are
 * used by configure to dynamically assign those values
 * to documentation files.
 */

/**
 * git_hash.h is generated by the build (see src/Makefile.am)
 *
 * GIT_HASH can have the following values:
 *   - a "git describe" string (hash/tag) on success.
 *   - "unknown" if git failed (e.g. tarball/no repo).
 *   - "n/a" if the header was never generated at all.
 *
 * We do the "__has_include" to not break packaging and quieten
 * IDEs over a not yet generated or otherwise missing header file.
 */
#ifdef __has_include
#if __has_include( "git_hash.h" )
#include "git_hash.h"
#else
#define GIT_HASH "n/a"
#endif
#else
#include "git_hash.h"
#endif

const char* version_string = "0.42";
const char* program_name = "nwipe";
const char* author_name = "Martijn van Brummelen";
const char* email_address = "git@brumit.nl";
const char* years = "2026";
const char* copyright = "Copyright\n"
                        "  Darik Horn <dajhorn-dban@vanadac.com>\n"
                        "  Andy Beverley <andy@andybev.com>\n"
                        "  Martijn van Brummelen <martijn@brumit.nl>\n"
                        "  Nick Law <shredos.eraser@gmail.com> (@PartialVolume)\n"
                        "  @desertwitch, @Knogle, and many others (refer to GitHub)\n"
                        "\n"
                        "This is free software; see the source for copying conditions.\n"
                        "There is NO warranty; not even for MERCHANTABILITY or\n"
                        "FITNESS FOR A PARTICULAR PURPOSE.\n";
const char* banner = "nwipe 0.42";
const char* git_hash_string = GIT_HASH;
