name: ci-ubuntu-latest-hard-std-c17

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_CFLAGS: "-O1 -g -std=c17 -Wall -Wextra -Wconversion -Wsign-conversion -Wsign-compare -Wshadow -Wfloat-conversion -Wuninitialized -Wformat-truncation -Wstrict-overflow=2 -Wcast-align -Wno-system-headers"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update system packages
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential pkg-config automake libncurses5-dev autotools-dev libparted-dev libconfig-dev libconfig++-dev dmidecode

      - name: Install meson build system
        run: sudo apt-get install -y meson ninja-build libjson-c-dev

      - name: Build libnvme dependency
        run: |
          wget https://github.com/linux-nvme/libnvme/archive/refs/tags/v1.16.1.tar.gz
          tar xvfz v1.16.1.tar.gz
          cd libnvme-1.16.1
          meson setup .build
          meson compile -C .build
          sudo meson install -C .build
          sudo ldconfig

      - name: Generate autogen files
        run: ./autogen.sh

      - name: Configure the program with more warnings
        run: ./configure CFLAGS="$BASE_CFLAGS" CXXFLAGS="$BASE_CFLAGS" --with-libnvme
  
      - name: Compile the program
        run: make CFLAGS="$BASE_CFLAGS -fanalyzer" CXXFLAGS="$BASE_CFLAGS -fanalyzer"
